name: Deploy to WebMadeIt

on: workflow_dispatch
#  push:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Create .env file
      run: touch .env
    - name: Write to .env file
      run: |
        echo REACT_APP_BASE_API_URL=${{ secrets.REACT_APP_BASE_API_URL }} >> .env
        echo REACT_APP_TOKEN_USR=${{ secrets.REACT_APP_TOKEN_USR }} >> .env
        echo REACT_APP_TOKEN_PWD=${{ secrets.REACT_APP_TOKEN_PWD }} >> .env
        echo REACT_APP_RECAPTCHA_SITEKEY=${{ secrets.REACT_APP_RECAPTCHA_SITEKEY }} >> .env

    - run: npm ci
    - run: npm run build --if-present

    - name: Sync files to sharedhosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_INTER_HOST }}
        username: ${{ secrets.FTP_WEBMADEIT_USR }}
        password: ${{ secrets.FTP_WEBMADEIT_PWD }}
        local-dir: ./build/
        server-dir: ./react-gha/